// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiJheZmmgZgyS2qPtHlU3_nVG8Z3TkY70',
    appId: '1:50127505382:web:794a8d82a4f7f68c6a3827',
    messagingSenderId: '50127505382',
    projectId: 'optimal-state-of-living-e79fa',
    authDomain: 'optimal-state-of-living-e79fa.firebaseapp.com',
    storageBucket: 'optimal-state-of-living-e79fa.firebasestorage.app',
    measurementId: 'G-490Q2FC53R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSx0ZKktJuDsPl8z-JWVb0MA6yUzBQ3v0',
    appId: '1:435993134541:android:05e54757479cbf07ac7084',
    messagingSenderId: '435993134541',
    projectId: 'optimal-state-of-living-123',
    storageBucket: 'optimal-state-of-living-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY4l9UynipCtOIlObK9vp5v2I4yU2Bu60',
    appId: '1:50127505382:ios:e2fc852b1b65c1fa6a3827',
    messagingSenderId: '50127505382',
    projectId: 'optimal-state-of-living-e79fa',
    storageBucket: 'optimal-state-of-living-e79fa.firebasestorage.app',
    iosBundleId: 'com.example.optimalStateOfLiving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY4l9UynipCtOIlObK9vp5v2I4yU2Bu60',
    appId: '1:50127505382:ios:e2fc852b1b65c1fa6a3827',
    messagingSenderId: '50127505382',
    projectId: 'optimal-state-of-living-e79fa',
    storageBucket: 'optimal-state-of-living-e79fa.firebasestorage.app',
    iosBundleId: 'com.example.optimalStateOfLiving',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiJheZmmgZgyS2qPtHlU3_nVG8Z3TkY70',
    appId: '1:50127505382:web:195cd631c430d6fc6a3827',
    messagingSenderId: '50127505382',
    projectId: 'optimal-state-of-living-e79fa',
    authDomain: 'optimal-state-of-living-e79fa.firebaseapp.com',
    storageBucket: 'optimal-state-of-living-e79fa.firebasestorage.app',
    measurementId: 'G-66LFMXDR1L',
  );

}